# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      # - run: npm run build
      - run: |
          echo @ruudra03:https://npm.pkg.github.com/ > ./.npmrc
          echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> ./.npmrc
      - run: npm publish
        working-directory: ./
        env:
          NPM_TOKEN: ${{ secrets.GHP_REGISTRY_TOKEN }}
